version: 2
updates:
  # Enable version updates for cargo
  - package-ecosystem: "cargo"
    directory: "/backend"
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  # App: Custom
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "daily"
  # App: External
  - package-ecosystem: "docker"
    directory: "/deploy/meilisearch"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/deploy/redis"
    schedule:
      interval: "daily"
  # Monitoring
  - package-ecosystem: "docker"
    directory: "/monitor/grafana"
    schedule:
      interval: "daily"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
