[package]
name = "tester"
version.workspace = true
edition.workspace = true

[package.metadata.cargo-shear]
ignored = ["prost"]

[dependencies]
bank = { path = "../bank", features = ["payloads"] }
prost = "0.14.1"
