[package]
name = "tester"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-shear]
ignored = ["prost"]

[dependencies]
bank = { path = "../backend/bank", features = ["payloads"] }
prost = "0.14.1"
