[alias]
docs = "doc --no-deps --open"
process = "run -p process --"
processv = "run -p process --features verbose --"
processl = "run -p process --features locations --"
server = "run -p server"
serverv = "run -p server --features verbose"
