[package]
name = "bank"
version.workspace = true
edition.workspace = true

[package.metadata.cargo-shear]
ignored = ["prost"]

[dependencies]
prost = "0.14.1"
reqwest = "0.12.28"

[build-dependencies]
prost-build = "0.14.1"
